version: 2

updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly

# https://github.com/microsoft/torchgeo/pull/603/files
- package-ecosystem: pip
  directory: "/requirements"
  schedule:
    interval: daily
  open-pull-requests-limit: 2
