version: 2

updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly

- package-ecosystem: pip-compile
  directory: "/requirements"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
